project:
  type: website
  output-dir: site
  render:
    - "index.qmd"
    - "presentations.qmd"
    - "blogs.qmd"
    - "blogs/"
    
format: 
  html:
    theme: 
      - cosmo
      - styles.scss

website:
  title: "Alice Hannah"
  sidebar:
    style: "docked"
    align: center
    title: "Alice Hannah"
    logo: "https://avatars.githubusercontent.com/u/36480969?v=4"
    tools: 
      - icon: github
        href: https://github.com/alice-hannah
        text: "Alice Hannah GitHub Profile"
    contents:
      - text: "About"
        file: index.qmd
      - presentations.qmd
      - blogs.qmd
