project:
  type: website
  output-dir: site
  render:
    - "index.qmd"

format: 
  html:
    theme: cosmo

website:
  title: "Alice Byers"
  sidebar:
    style: "docked"
    align: center
    title: "Alice Byers"
    logo: "https://avatars.githubusercontent.com/u/36480969?v=4"
    tools: 
      - icon: github
        href: https://github.com/alicebyers5
        text: "Alice Byers GitHub Profile"