---
title: Presentations
format: 
  html:
    toc: true
---

## 2023

### RAP in Practice

Slides for presentation on RAP (Reproducible Analytical Pipelines) in Practice at the [Scottish Government Digital Academy Fit for the Future](https://digitalacademy.arlo.co/courses/112-fit-for-the-future-leading-a-modern-statistical-service?e=2f5fd1d61f1240239af248e29ede693d) event on 16 November 2023.

[Slides](../2023-11_fit-for-the-future/slides_fftf.html){.external target="_blank"}


### Accessible data visualisations

Slides for the Scottish Government Accessibility Champions network meeting on 19 October 2023.

[Slides](../2023-10-19_accessible-data-vis/slides.html){.external target="_blank"}

### Introduction to RAP

A version of the previous [RAP in the Scottish Government](#rap-in-the-scottish-government) presentation edited for the [Data Science Accelerator](https://www.gov.scot/publications/data-science-accelerator/) 2023 cohort meeting on 11 October 2023.

[Slides](../2023-10-11_RAP-DSAP/slides.html){.external target="_blank"}

### Creating accessible charts in R using sgplot

Slides for the Scottish Government analytical seminar on use of the [sgplot](https://datasciencescotland.github.io/sgplot/) package on 19 June 2023. This presentation was jointly delivered with Lee Bunce from the Office of the Chief Statistician.

[Slides](../2023-06-19_sgplot/slides.html){.external target="_blank"}

### RAP in the Scottish Government

Slides for the Scottish Government Analyst Induction event on Data Tools and Standards on 13 June 2023.

[Slides](../2023-06-13_RAP-in-SG/slides.html){.external target="_blank"}

### Introduction to Git and GitHub

Slides for non-technical presentation to the Scottish Government [Data Standards and Open Data Community of Practice](https://www.eventbrite.co.uk/e/git-and-github-for-reproducible-data-analysis-tickets-558593497187) on 27 April 2023.

[Slides](../2023-04-27_git-github-intro/slides.html){.external target="_blank"}

## 2022

### RAP in Practice

Slides for presentation on RAP (Reproducible Analytical Pipelines) in Practice at the [Scottish Government Digital Academy Fit for the Future](https://digitalacademy.arlo.co/courses/112-fit-for-the-future-leading-a-modern-statistical-service?e=2f5fd1d61f1240239af248e29ede693d) event on 23 November 2022.

[Slides](https://github.com/alicebyers5/presentations-and-blogs/raw/main/2022-11-23_fit-for-the-future/rap-in-practice.pptx){.download target="_blank"}

### School Information Dashboard RAP

Slides for presentation on [School Information Dashboard Reproducible Analytical Pipeline (RAP) project](https://github.com/DataScienceScotland/school-information-dashboard) at the [Scottish Government R User Day](https://github.com/DataScienceScotland/R-user-day-talks) on 5 October 2022. This presentation was jointly delivered with [Laura Stott](https://github.com/LauraStott). 

[Slides](https://github.com/alicebyers5/presentations-and-blogs/raw/main/2022-10-05_school-information-dashboard-rap/school-information-dashboard-rap.pptx){.download target="_blank"}

## 2020

### Creating Management Reports using flexdashboard

Slides for presentation on creating management reports using the [`flexdashboard`](https://rmarkdown.rstudio.com/flexdashboard/) R package at the [PHI useR Group](https://github.com/Public-Health-Scotland/PHI-useR-group) meeting on 25 February 2020.

[Slides](../2020-02-25_flexdashboard/slides.html){.external target="_blank"}
